nuls:
  api:
    timeout: 10000
    explorer:
      host: https://testnet.nuls.world
      base: ''
      resources:
        utxos: /utxos/__ADDRESS__
        balance: /balance/__ADDRESS__
        broadcast: /broadcast
        transaction: /transaction/__HASH__
        contractMethods: /contract/__ADDRESS__/methods
        contractView: /contract/__ADDRESS__/view
        # utxos: /addresses/outputs/__ADDRESS__.json
        # broadcast: /broadcast
        # transaction: /transactions/__HASH__.json
        # contractMethods: /addresses/contracts/__ADDRESS__/methods.json
        # contractView: /addresses/contracts/call