nuls:
  api:
    timeout: 10000
    apiserver:
      host: http://testnet.apiserver.nuls.io
      base: /nuls
    explorer:
      host: https://nuls.world
      base: ''
      resources:
        utxos: /addresses/outputs/__ADDRESS__.json
        broadcast: /broadcast
        methods: /api/contract/info/wallet/__ADDRESS__
        view: /api/contract/view
        call: /api/contract/call