nuls:
  api:
    timeout: 10000
    apiserver:
      host: http://testnet.apiserver.nuls.io
      base: /nuls
    explorer:
      host: https://testnet.nuls.world
      base: ''
      resources:
        utxos: /addresses/outputs/__ADDRESS__.json
        broadcast: /broadcast
        transaction: /transactions/__HASH__.json
        contractMethods: /addresses/contracts/__ADDRESS__/methods.json
        contractView: /addresses/contracts/call