nuls:
  api:
    timeout: 5000
    apiserver:
      host: http://testnet.apiserver.nuls.io
      port: ''
      base: /nuls
    transaction:
      host: https://nuls.world
      port: 443
      base: /api/contract/
    utxo:
      host: https://nuls.world
      port: 443
      base: ''
      resources:
        address: /addresses/outputs/__ADDRESS__.json
    contract:
      host: http://localhost
      port: 8001
      base: /api/contract/
      resources:
        methods: /info/wallet/__ADDRESS__
        view: /view
        call: /call