nuls:
  api:
    timeout: 10000
    blockTime: 10
    blocksMinedTimeout: 15
    explorer:
      host: https://testnet.nuls.world
      base: ''
      resources:
        utxos: /utxos/__ADDRESS__
        balance: /balance/__ADDRESS__
        broadcast: /broadcast
        lastHeight: /last-height/
        block: /block/__HEIGHT_OR_HASH__?full=true
        transaction: /transaction/__HASH__
        contractMethods: /contract/__ADDRESS__/methods
        contractView: /contract/__ADDRESS__/view
        contractCallGas: /contract/__ADDRESS__/call/gas
        contractCallValidate: /contract/__ADDRESS__/call/validate
        # utxos: /addresses/outputs/__ADDRESS__.json
        # broadcast: /broadcast
        # transaction: /transactions/__HASH__.json
        # contractMethods: /addresses/contracts/__ADDRESS__/methods.json
        # contractView: /addresses/contracts/call